#Author:SapientS
#Date:08/02/2015
#Package Installer for JAT-Java Virtual Machine Auto Tuning Tool

JATT_Version="Version 1.0"
echo "Installing Packages for JATT $JATT_Version"
echo "# Generated by Application"
export http_proxy='http://$1/'

#Packages needed for Opentuner.
sudo apt-get install build-essential
sudo apt-get install gnuplot
sudo apt-get install libpng-dev
sudo apt-get install libsqlite3-dev
sudo apt-get install python-dev
sudo apt-get install sqlite3

#Installing OpenTuner
sudo apt-get install python-pip
sudo pip install opentuner --proxy=$http_proxy

#Installing JATT Packages
sudo pip install pandas --proxy=$http_proxy

